CREATE TABLE "vehicle_pickup_notices" ("id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY, "vehicle_id" bigint NOT NULL, "origin_business_order_id" bigint NOT NULL, "notified_at" timestamp with time zone NOT NULL, "notified_by" bigint NOT NULL, "daily_rate_minor" bigint NOT NULL, "free_days" integer NOT NULL, "paused_at" timestamp with time zone, "paused_by_business_order_id" bigint, "paused_accrued_minor" bigint, "picked_up_at" timestamp with time zone, "picked_up_by" bigint, CONSTRAINT "vehicle_pickup_notices_rate_positive" CHECK (daily_rate_minor > 0 and free_days >= 0), CONSTRAINT "vehicle_pickup_notices_pause_complete" CHECK (num_nonnulls(paused_at, paused_by_business_order_id, paused_accrued_minor) in (0, 3)));--> statement-breakpoint
ALTER TABLE "vehicle_pickup_notices" ADD CONSTRAINT "vehicle_pickup_notices_vehicle_fk" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE restrict;
ALTER TABLE "vehicle_pickup_notices" ADD CONSTRAINT "vehicle_pickup_notices_origin_order_fk" FOREIGN KEY ("origin_business_order_id") REFERENCES "business_orders"("id") ON DELETE restrict;
ALTER TABLE "vehicle_pickup_notices" ADD CONSTRAINT "vehicle_pickup_notices_notified_by_fk" FOREIGN KEY ("notified_by") REFERENCES "staff_accounts"("id") ON DELETE restrict;
ALTER TABLE "vehicle_pickup_notices" ADD CONSTRAINT "vehicle_pickup_notices_paused_order_fk" FOREIGN KEY ("paused_by_business_order_id") REFERENCES "business_orders"("id") ON DELETE restrict;
ALTER TABLE "vehicle_pickup_notices" ADD CONSTRAINT "vehicle_pickup_notices_picked_by_fk" FOREIGN KEY ("picked_up_by") REFERENCES "staff_accounts"("id") ON DELETE restrict;
CREATE UNIQUE INDEX "vehicle_pickup_notices_origin_uq" ON "vehicle_pickup_notices" ("origin_business_order_id"); CREATE UNIQUE INDEX "vehicle_pickup_notices_one_active_vehicle_uq" ON "vehicle_pickup_notices" ("vehicle_id") WHERE "picked_up_at" IS NULL; CREATE INDEX "vehicle_pickup_notices_pending_idx" ON "vehicle_pickup_notices" ("vehicle_id", "notified_at");--> statement-breakpoint
CREATE OR REPLACE FUNCTION pause_vehicle_pickup_notice_for_new_order() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN UPDATE vehicle_pickup_notices AS notice SET paused_at = NEW.created_at, paused_by_business_order_id = NEW.id, paused_accrued_minor = greatest(0, ((NEW.created_at AT TIME ZONE 'America/Jamaica')::date - (notice.notified_at AT TIME ZONE 'America/Jamaica')::date) - notice.free_days) * notice.daily_rate_minor WHERE notice.vehicle_id = NEW.vehicle_id AND notice.picked_up_at IS NULL AND notice.paused_at IS NULL AND NEW.id <> notice.origin_business_order_id AND NEW.created_at >= notice.notified_at; RETURN NEW; END; $$;--> statement-breakpoint
CREATE TRIGGER business_orders_pause_vehicle_pickup_notice AFTER INSERT ON business_orders FOR EACH ROW EXECUTE FUNCTION pause_vehicle_pickup_notice_for_new_order();
