import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { Blob as NodeBlob } from "node:buffer";
import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { InspectionPdfDownload } from "../../src/components/orders/inspection-pdf-download";
import { createFormalInspectionPdf } from "../../src/lib/orders/formal-inspection-pdf-download";
import { inspectionDetailFixture } from "../fixtures/inspection-detail";
import { printPdfBytes } from "../../src/lib/orders/ir-pdf-print";
vi.mock("../../src/lib/orders/formal-inspection-pdf-download", () => ({ createFormalInspectionPdf: vi.fn() }));
vi.mock("../../src/components/orders/pdf-canvas-preview", () => ({ PdfCanvasPreview: ({ bytes, onError }: { bytes: Uint8Array; onError: (message: string) => void }) => <div data-testid="actual-pdf-preview" data-bytes={Array.from(bytes).join(",")}><button onClick={() => onError("预览资源失败")}>模拟预览失败</button></div> }));
vi.mock("../../src/lib/orders/ir-pdf-print", () => ({ printPdfBytes: vi.fn().mockResolvedValue({}) }));
beforeEach(() => { vi.stubGlobal("Blob", NodeBlob); vi.mocked(printPdfBytes).mockReset().mockResolvedValue({ attachmentId: "test", language: "zh", fileName: "test.pdf" }); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.mocked(createFormalInspectionPdf).mockReset(); });
it("keeps failure recoverable and exposes a correctly named downloadable file after retry", async () => {
  vi.stubGlobal("URL", { createObjectURL: vi.fn(() => "blob:report"), revokeObjectURL: vi.fn() });
  vi.mocked(createFormalInspectionPdf).mockRejectedValueOnce(new Error("字体资源未加载")).mockResolvedValueOnce(new Blob());
  render(<InspectionPdfDownload detail={inspectionDetailFixture} language="en" english={false} />);
  fireEvent.click(screen.getByRole("button", { name: "生成 PDF 文件" }));
  expect((await screen.findByRole("alert")).textContent).toContain("字体资源未加载");
  fireEvent.click(screen.getByRole("button", { name: "生成 PDF 文件" }));
  const link = await screen.findByRole("link", { name: "下载 PDF" });
  expect(link.getAttribute("download")).toBe("IR-20260905-0009-EN.pdf");
  expect(link.getAttribute("href")).toBe("blob:report");
  expect(screen.queryByRole("alert")).toBeNull();
});
it("does not deliver an obsolete language and prevents duplicate generation", async () => {
  const makeUrl = vi.fn(() => "blob:report");
  vi.stubGlobal("URL", { createObjectURL: makeUrl, revokeObjectURL: vi.fn() });
  let finish!: (value: Blob) => void;
  vi.mocked(createFormalInspectionPdf).mockImplementation(() => new Promise((resolve) => { finish = resolve; }));
  const view = render(<InspectionPdfDownload detail={inspectionDetailFixture} language="zh" english={false} />);
  const button = screen.getByRole("button", { name: "生成 PDF 文件" });
  fireEvent.click(button); fireEvent.click(button);
  expect(createFormalInspectionPdf).toHaveBeenCalledTimes(1);
  view.rerender(<InspectionPdfDownload detail={inspectionDetailFixture} language="en" english={false} />);
  await act(async () => finish(new Blob()));
  expect(makeUrl).not.toHaveBeenCalled();
  expect(screen.queryByRole("link", { name: "下载 PDF" })).toBeNull();
  expect(screen.getByRole("button", { name: "生成 PDF 文件" })).toBeTruthy();
});
it("cancels generation and revokes the finished file when the source changes", async () => {
  const revoke = vi.fn();
  vi.stubGlobal("URL", { createObjectURL: vi.fn(() => "blob:report"), revokeObjectURL: revoke });
  let finish!: (value: Blob) => void;
  vi.mocked(createFormalInspectionPdf).mockImplementationOnce(() => new Promise((resolve) => { finish = resolve; })).mockResolvedValueOnce(new Blob());
  const view = render(<InspectionPdfDownload detail={inspectionDetailFixture} language="zh" english={false} />);
  fireEvent.click(screen.getByRole("button", { name: "生成 PDF 文件" }));
  fireEvent.click(screen.getByRole("button", { name: "取消生成" }));
  await act(async () => finish(new Blob()));
  expect(screen.queryByRole("link")).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "生成 PDF 文件" }));
  await screen.findByRole("link", { name: "下载 PDF" });
  view.rerender(<InspectionPdfDownload detail={inspectionDetailFixture} language="en" english={false} />);
  expect(revoke).toHaveBeenCalledWith("blob:report");
  expect(screen.queryByRole("link")).toBeNull();
});
it("previews the exact downloadable PDF bytes and retries preview without regenerating the file", async () => {
  vi.stubGlobal("URL", { createObjectURL: vi.fn(() => "blob:report"), revokeObjectURL: vi.fn() });
  const onReadyChange = vi.fn();
  vi.mocked(createFormalInspectionPdf).mockResolvedValue(new Blob([Uint8Array.from([37, 80, 68, 70, 7])]));
  render(<InspectionPdfDownload detail={inspectionDetailFixture} language="en" english={false} onReadyChange={onReadyChange} />);
  fireEvent.click(screen.getByRole("button", { name: "生成 PDF 文件" }));
  const preview = await screen.findByTestId("actual-pdf-preview");
  expect(preview.getAttribute("data-bytes")).toBe("37,80,68,70,7");
  expect(onReadyChange).toHaveBeenLastCalledWith(true);
  fireEvent.click(screen.getByRole("button", { name: "模拟预览失败" }));
  expect(screen.getByRole("link", { name: "下载 PDF" })).toBeTruthy();
  fireEvent.click(screen.getByRole("button", { name: "重新加载预览" }));
  expect(screen.getByTestId("actual-pdf-preview")).not.toBe(preview);
  expect(createFormalInspectionPdf).toHaveBeenCalledTimes(1);
});
it("prints the preview bytes and keeps download and retry available after print failure", async () => {
  vi.stubGlobal("URL", { createObjectURL: vi.fn(() => "blob:report"), revokeObjectURL: vi.fn() });
  vi.mocked(createFormalInspectionPdf).mockResolvedValue(new Blob([Uint8Array.from([37, 80, 68, 70, 9])]));
  vi.mocked(printPdfBytes).mockRejectedValueOnce(new Error("打印未启动，请下载 PDF 后打印"));
  render(<InspectionPdfDownload detail={inspectionDetailFixture} language="zh" english={false} />);
  fireEvent.click(screen.getByRole("button", { name: "生成 PDF 文件" }));
  fireEvent.click(await screen.findByRole("button", { name: "打印此 PDF" }));
  expect((await screen.findByRole("alert")).textContent).toContain("打印未启动");
  const [file, , signal] = vi.mocked(printPdfBytes).mock.calls[0];
  expect(Array.from(file.bytes)).toEqual([37, 80, 68, 70, 9]);
  expect(file.metadata.fileName).toBe("IR-20260905-0009-ZH.pdf");
  expect(signal?.aborted).toBe(false);
  expect(screen.getByRole("link", { name: "下载 PDF" })).toBeTruthy();
  fireEvent.click(screen.getByRole("button", { name: "打印此 PDF" }));
  await act(async () => {});
  expect(printPdfBytes).toHaveBeenCalledTimes(2);
  expect(screen.queryByRole("alert")).toBeNull();
});
it("aborts pending print preparation when the language changes", async () => {
  vi.stubGlobal("URL", { createObjectURL: vi.fn(() => "blob:report"), revokeObjectURL: vi.fn() });
  vi.mocked(createFormalInspectionPdf).mockResolvedValue(new Blob());
  vi.mocked(printPdfBytes).mockImplementation(() => new Promise(() => {}));
  const view = render(<InspectionPdfDownload detail={inspectionDetailFixture} language="zh" english={false} />);
  fireEvent.click(screen.getByRole("button", { name: "生成 PDF 文件" }));
  fireEvent.click(await screen.findByRole("button", { name: "打印此 PDF" }));
  const signal = vi.mocked(printPdfBytes).mock.calls[0][2];
  view.rerender(<InspectionPdfDownload detail={inspectionDetailFixture} language="en" english={false} />);
  expect(signal?.aborted).toBe(true);
  expect(screen.queryByRole("link", { name: "下载 PDF" })).toBeNull();
});
