"use client";
import { useEffect, useState } from "react";
import { AlertCircle, Car, RefreshCw } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { fetchFormalParking, notifyFormalPickup, recordFormalPickup, type FormalParkingWorkspace } from "@/lib/api/formal-parking";
import { formatDateTime, formatJMDFull } from "@/lib/utils";

export function FormalParkingWorkspace() {
  const [data, setData] = useState<FormalParkingWorkspace | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const reload = () => { setLoading(true); setError(null); fetchFormalParking().then(setData).catch((caught) => setError(caught instanceof Error ? caught.message : "待取车读取失败")).finally(() => setLoading(false)); };
  useEffect(reload, []);
  const act = async (operation: () => Promise<unknown>) => { try { await operation(); reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : "操作失败"); } };
  return <div data-testid="parking-workspace" className="px-3 py-3 sm:px-5"><div className="mx-auto w-full max-w-[1720px]"><PageHeader breadcrumb="收付款与交车" title="待取车" description="只从正式交单与车辆当前 Business Order 状态生成候选；不记录停车位置。" />
    <div className="mt-3 rounded-2xl border border-blue-100 bg-blue-50/60 px-4 py-3 text-xs text-ink dark:border-slate-600 dark:bg-slate-800/60">通知后新建 Business Order 会暂停停车流程；暂停前已产生金额保留，提醒前台决定是否免除。</div>
    {loading ? <div data-testid="parking-loading" className="mt-3 h-48 animate-pulse rounded-2xl bg-slate-100" /> : null}{error ? <div className="mt-3 rounded-2xl border border-rose-200 p-5 text-center"><AlertCircle className="mx-auto text-rose-600" /><p className="mt-2 text-sm">{error}</p><button onClick={reload} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-lg border border-line px-4 text-sm"><RefreshCw size={14}/>重试</button></div> : null}
    {!loading && !error ? <section data-testid="parking-cases" className="mt-3 rounded-[22px] border border-line bg-white/75 p-3 shadow-card dark:border-slate-700 dark:bg-slate-900/35"><p className="text-xs font-semibold text-ink-soft">待取车/通知候选（{data?.items.length ?? 0}）</p>{data?.items.length ? <div className="mt-3 space-y-2">{data.items.map((item) => <article key={item.kind === "candidate" ? `candidate-${item.vehicleId}` : item.noticeId} className="rounded-2xl border border-line bg-white p-3 dark:border-slate-700 dark:bg-slate-800/70"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="inline-flex items-center gap-1 text-sm font-bold"><Car size={14}/>{item.plateDisplay ?? "未录车牌"} · {item.orderNo}</p><p className="mt-1 text-xs text-ink-soft">{item.customerName}</p>{item.kind === "notice" ? <p className="mt-1 text-xs text-ink-soft">通知 {formatDateTime(item.notifiedAt)}{item.status === "parking_paused_needs_front_desk_decision" ? ` · 已暂停，保留金额 ${formatJMDFull((item.accruedParkingMinor ?? 0) / 100)}` : " · 等待实际取车"}</p> : <p className="mt-1 text-xs text-emerald-700">正式交单完成，当前没有其他进行中的 Business Order</p>}</div><div>{item.kind === "candidate" ? <button data-testid={`parking-notify-${item.vehicleId}`} onClick={() => void act(() => notifyFormalPickup(item.vehicleId))} className="min-h-9 rounded-lg bg-primary px-3 text-xs font-semibold text-white">记录通知</button> : <button data-testid={`parking-pickup-${item.noticeId}`} onClick={() => void act(() => recordFormalPickup(item.noticeId))} className="min-h-9 rounded-lg bg-emerald-600 px-3 text-xs font-semibold text-white">记录实际取车</button>}</div></div></article>)}</div> : <div data-testid="parking-empty" className="py-16 text-center text-sm text-ink-soft">暂无待取车或通知候选车辆。</div>}</section> : null}
  </div></div>;
}
